### ISSUE TITLE
DOCS: Update NumPy docs related to GitHub

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#1]
See https://numpy.org/devdocs/dev/index.html

There are multiple references throughout the website that refer to a GitHub username and password.

> Enter your GitHub username and password (repeat contributors or advanced users can remove this step by connecting to GitHub with SSH).

The entire GitHub authentication system has been replace with PATs.  The documentation needs to be updated. 
- I searched NumPy's issue tracker for a related issue. none found. 
  - https://github.com/numpy/numpy/issues?q=is%3Aissue+is%3Aopen+github+password
  - https://github.com/numpy/numpy/pulls?q=is%3Apr+is%3Aopen+github+password

This looks like a great issue we can get started with.

**Comment by bmwoodruff** [comment]
There are many ways this could unfold, with lots of possible different solutions.  I'm not sure what the best option is, and I'm guessing a discussion will need to happen on NumPy's site eventually.  We could discuss and develop a possible solution here first, and then ask for feedback on NumPy's issue tracker before submitting a PR. Or, we could just get started with the discussion on NumPy's issue tracker.  I've got multiple idea for how to fix the issue, and would be happy to chime in with them, but I'd also love to let someone on the team give it a try first.

**Comment by ogidig5** [comment]
@bmwoodruff I have gone through the documentation you referenced: (https://numpy.org/devdocs/dev/index.html)

Indeed, Personal Access Tokens (PATs) have replaced the traditional GitHub Username and Password authentication. 

I think we can have a discussion here first about ways to solve this issue. For example, we can keep on searching for any other possible instances/locations where this traditional authentication method needs to be updated in the existing NumPy documentations (If any is available).

Once identified, we can systematically replace these references with clear instructions on generating and utilizing Personal Access Tokens (PATs) for authentication purposes. As a team, we can come up with a refined set of instructions of how to set up PATs. We can then ask for feedback on NumPy's issue tracker before submitting a PR.

**Comment by ogidig5** [comment]
@bmwoodruff For a start, I will be practicing how to do a pull request on this issue today. Let me start with the first option you've suggested above. I hope all goes well.

**Comment by bmwoodruff** [comment]
@ogidig5's PR finished this task.
