### ISSUE TITLE
Discussion: Prompt Design and Engineering

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#11]
Let's use this as a place to document general findings on prompt design and engineering with Nebari and Ragna. Feel free to start a new issue at any time if you want to discuss specific findings that you feel deserves it's own discussion.

**Comment by andrewtggreene** [comment]
I created an issue on the resource repository that has a link to a very valuable resource for understanding how to create better prompts and different techniques that are used. 

Here's the issue:
[https://github.com/possee-org/possee-resources/issues/1](https://github.com/possee-org/possee-resources/issues/1)

**Comment by bmwoodruff** [comment]
Using the ideas @andrewtggreene shared above, I built a docstrings prompt generator (see https://github.com/possee-org/genai-numpy/issues/16). 

We could use a similar generator for examples (feed in several functions with docstrings, followed by the examples in the codebase, and then feed in a function with docstrings that we'd like to produce examples for). Anyone want to tackle this?

**Comment by andrewtggreene** [comment]
@bmwoodruff I'll take a look at this and see what I can come up with. If anyone else wants to work on this feel free.
