### ISSUE TITLE
Review: AI Gen Examples for ma.argsort

### ISSUE THREAD

**Issue by otieno-juma** [possee-org/genai-numpy#110]
**Link to your fork:**

https://github.com/numpy/numpy/compare/main...otieno-juma:numpy:ai-examples-ma-argsort

**Checks**

```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests && spin lint
```
- [ ] All tests have passed
- [ ] A visual inspection of the generated docs is correct

**Acceptance Criteria:**

Close when the following are complete, in order:
- [ ] Reviewed by @bmwoodruff
- [ ] Any suggestions to fork have been merged.
- [ ] Reviewed by Numpy Mainter:

When all tasks are complete:
- [ ] Submitted as PR to NumPy.

![argsort function](https://github.com/possee-org/genai-numpy/assets/103896399/9a250f2b-0b79-4862-83dd-5fe6fdfe7e5f)

**Comment by bmwoodruff** [comment]
The example doesn't involve any sorting at all, rather it just defines an array and then shows it.  This example is definitely not worth adding to the codebase. 

We'll need to refine our prompt to get better examples, if we hope to add them to the codebase.  Focus on the ones that have no examples, or try creating better prompts.  

You now know what it takes to get something to pass the tests, and prepare it for inclusion.  Now we just need better examples, or focus on different aspects of the docstring.
