### ISSUE TITLE
BUG: Numpy Cheat Sheet

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#113]
@jud-sdev, here's some feedback related to the cheatsheet you created. 

1. What AI tool did you use?  What was your prompt? How did you create it?  It would be great to have that documented. This would help others make improvements. Did AI create the whole thing? Did it just create parts of it and you compiled it together? More info would be great if/when you plan to share this with others. 
2. Some of the commands do not run. Ideally, the sheet would run if someone hit "Run All". That does not happen right now. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)
```
```
------------------------------------------------------------------------------------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
...
LinAlgError: 1-dimensional array given. Array must be at least two-dimensional
```

3. Have you made more than one sheet with AI, and compared several?  There are way more functions in Numpy than what you have listed on this sheet? In particular, the LinAlg unit alone has more functions with options that you have listed here. The feedback on the original issue in NumPy as that maybe a cheatsheet per module would be nice.  Having more than one to compare/contrast could be great.
4. The original idea behind the cheatsheet came up in a documentation meeting. Those happen now on Monday at a time I think you could attend. Having multiple made and going to the documentation meeting to get feedback would probably be the best way to move forward on using AI to create a cheatsheet.

**Comment by jud-sdev** [comment]
I used GPT-4o to create the entire cheatsheet. While I know that not all functions were captured, I focused on the basic ones. Going forward, I will create the cheatsheets for each module separately and make a pull request for each one. I'll also fix the errors in the previous cheatsheets and attach my prompts for documentation purposes.

When you say "more than one to compare/contrast," do you mean I should create different versions of the cheatsheet and then make comparisons?

I apologize for missing the Monday meeting. I'll make sure to attend the subsequent ones.

**Comment by jud-sdev** [comment]
I've corrected the errors and made a pull request: https://github.com/possee-org/genai-numpy/pull/119. Since there are several functions to be included in the cheatsheet, I will create it module-wise and make a pull request for each module. I will also document my prompts and the AI tools used in generating them.

**Comment by bmwoodruff** [comment]
> When you say "more than one to compare/contrast," do you mean I should create different versions of the cheatsheet and then make comparisons?

I'm not sure what direction to head here. I have not been at either of the last 2 document meetings, where this topic was brought up, and then discussed.  You can view the agenda and brief notes and see that they talked about it.  I don't know which direction to head, or exactly what this might look like.  It'd definitely something that AI could help with. My thoughts are that having multiple versions of things that AI generated, along with the prompts you used to generate them (all publicly visible) could help spark ideas for improvement.

**Comment by bmwoodruff** [comment]
Note that AI will completely get wrong some things. For example, the way to use random number in Numpy has been updated an changed from what the sheet you uploaded says.  To find the new way, you'd have to do some reading on random number generation.  I'm not sure AI will capture that correctly, but might with the correct types of prompts. 

Before proceeding more on this, I'd strongly suggest you review the notes from the documentation meetings.  If making one sheet per module sounds great, then go for it, but please make sure you read the notes from meeting, view the sheets that have already been created (they provided a long list of examples on the Numpy issue page related to this).

**Comment by jud-sdev** [comment]
Any idea on how I can get the notes from the documentation meeting?

**Comment by bmwoodruff** [comment]
The community calendar has links to all meeting. The last link on the page https://numpy.org/community/ takes you to the calendar for many groups. The link for this last Monday has a meeting notes link.
