### ISSUE TITLE
Manual Example Generation

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#27]
As you do each of the following, keep track of difficult spots. If you hit a snag somewhere, share.

- Select a function that's missing examples. 
- Do a google search to find uses of that function and download the top 10 results as html (or PDF). Optional: Try different search options to see which one returns .
- Use an example generator (Andrew's work) to create multiple examples with just Llama 3.
- Use an example generator withLlama 3 and Ragna and the 10 google search results.
- Run the examples against the current dev build of NumPy. Save the output (compare with generated if any).
- Review the work yourself. Are the examples useful and/or helpful?
- Insert the example(s) into the proper file in the NumPy codebase.
- Build the docs and run the testing suite on your example. 
- Create a branch, add the file to that branch.
- Commit the changes, with a proper commit message.
- Push to your repo online.
- Leave a message in Zulip for Ben to review the work. 

We want something that will automate all, or most, of this. At this point, try doing each step without automation. We need to see where we are missing parts. We also need an environment where we can do all of these steps in one place.

**Comment by bmwoodruff** [comment]
You can find functions that are missing examples at
- https://www.github.com/numpy/numpy/issues/21351#issuecomment-2125078646

**Comment by bmwoodruff** [comment]
As a fun aside, you can add `www` to the start of a link to a github issue, and then it will generate a hyperlink to the topic WITHOUT cross referencing. See https://www.github.com/orgs/community/discussions/23123 . I wish I knew this weeks ago.

**Comment by ogidig5** [comment]
Here are the changes I've pushed to my fork: https://github.com/numpy/numpy/compare/main...ogidig5:numpy:add-svdvals-example

While the function examples are working, I realized there's a problem on line 1852. I used from `scipy.linalg import svdvals`, but that shouldn't be the case since this is purely a NumPy documentation. I wondered why `from numpy.linalg import svdvals` doesn't work, but this could be that I may not be using the latest version of NumPy.

Even though there are definitely some formatting changes needed, I just decided to push my updates to my fork so that I can fully go through issue #27 and get a better understanding of the entire process ( i.e. From generating examples to pushing changes to my fork). I'm looking forward to your insights.

Here's a snapshot of the docs I built:
![sdvals-function](https://github.com/possee-org/genai-numpy/assets/82846833/7ded6d68-e06b-488e-8be4-ea782f670a48)

**Comment by bmwoodruff** [comment]
Thanks for posting @ogidig5 .  This provides an excellent example of a few issues and things we'll need to decide on:

- Notice that AI brought in the library scipy.linalg.  The reason why is that `np.linalg.svdvals` is new to NumPy 2.0.  It won't find any examples on the web, so AI imported what it thought should be imported.  This is a problem. 
- How should we call functions?  I'm thinking we should always stick with `np.*` as this makes it easier to search for that precisely.  So hopefully we can coax or coerce AI to always call functions this way.  Here the hope would be `np.linalg.svdvals`, though does `np.svdvals` work (as suggested at the start of the docstring).
- What we search for on the web, and what we use in code, are two different things. I found that out when looking for examples for `np.ma.outer`.  
- Should comments such as `#Basic usage (square matrix)` be included as text between the examples, or inside the code?  I'm guessing between examples. 
- The AI suggested names are quite long. Do we really want to use such long names when `A` works just as well as `matrix_3x3`.  How do we get AI to simplify this.  
- Do we really need to save the name of the output, and then call the output (which is what AI did). 
- Is three examples needed?  The 2 by 2 and 3 by 3 examples are not very different. Not sure what the right answer is here.  

These area  few of the questions we'll need to address.  I have a couple more:
- Did you run `python tools/refguide_check.py --doctests` to make sure your examples pass the tests?
- Have you run `spin tests` to see if any changes you made caused problems with the codebase (shouldn't be an issue as this is all in the docstrings). 
- Did you follow the "See Also" section and compare with their examples?
- The introduction mentions that this is the same as calling `np.svd(...)` with some other options inside. It would be really nice if one of the generated examples showed that this was true.

**Comment by bmwoodruff** [comment]
I went to the documentation meeting today. 
- We will need to read the style docs again, but there didn't appear to be any preferred way to import functions (other than `import numpy as np`).  I prefer that we always use `np.module.function` as the way we call functions. 
- Comments should be between examples, not embedded in them.  It would be great if our example generator could do that. 
- Long names are not needed, nor wanted. We'll need to figure out how to get that to occur.
- There is no need to save the output and then call it.  Just run the function (without naming the output). 
- Low quality examples are discouraged. This is subjective, and we'll have to figure it out together via trial and error.  
They do want examples for functions that are similar to (or even aliases of) other functions.  So all the functions listed above are worth looking at. They hope that the examples provide something more than what can be found by following the "see also" section.  

Good news, we have some things working, and with a bit of refinement I think we can start submitting things to Chuck soon (and then on to PRs).
