### ISSUE TITLE
Task: Introduction to Nebari

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#4]
We'll each need an introduction to Nebari.  @bmwoodruff will meet with each student mentor, and then the mentors will meet with the interns. After you have gotten into Nebari, please do the following:
* Boot up a T4 GPU Instance 1x machine (third option down should be enough for testing with the smaller LLMs). 
* Create a folder under /shared/users that has your username.
* Copy the initial examples into your folder. 
* Practice running the examples. Running both examples, without restarting your kernels, should result in an memory overflow error.  make sure you encounter that. 
* Practice using nvidia-smi to monitor the GPU usage.
* Familiarize yourself with the code. You are welcome to change parameters and explore. The chat interface on the smaller Llama instance is quick for initial testing.  The asynchronous example will be much more useful when we work with the larger Llama model which will hopefully produce better results. 
* Leave a comment below when you feel you've completed this Task

**Comment by bmwoodruff** [comment]
Andrew and I met yesterday. I've completed the above.

**Comment by andrewtggreene** [comment]
I think we should add a task to make sure that we are able to shut down the server after use. I almost forgot this part while I was using this the other day until I heard my computer humming quite loudly.

**Comment by bmwoodruff** [comment]
> I think we should add a task to make sure that we are able to shut down the server after use. I almost forgot this part while I was using this the other day until I heard my computer humming quite loudly.

@andrewtggreene , the server is running remotely, so hopefully shouldn't be consuming your local resources. Whenever I am done, I just close the browser window I was using, and then after about 15 minutes of inactivity I believe the remote machine spins down.
