### ISSUE TITLE
Task: Polish up the examples for the `svdvals` function 

### ISSUE THREAD

**Issue by ogidig5** [possee-org/genai-numpy#49]
Description:

Last week, I created a branch on my GitHub to add examples to the svdvals function. After pushing the changes to my fork, I received some feedback to refine my examples. I have now implemented the suggested changes to my svdvals function example, removed the second example, and pushed the updated changes to my fork again. You can view the updates here: https://github.com/numpy/numpy/compare/main...ogidig5:numpy:add-svdvals-example

Here's what reflects when the docs build:
![Cleaned svdvals example](https://github.com/possee-org/genai-numpy/assets/82846833/dafca299-e165-4f37-9105-b94c3a40cb7c)

**Acceptance Criteria:**

- [x] List things here.

**Comment by bmwoodruff** [comment]
George, I'm trying to guess what the mns and svns stand for, and it's not obvious at all. As a reader of the examples, I'm left trying to guess what that abbreviation stood for. Using `matrix_non_square` is much better. You did get rid of naming the output, then calling the output, which is an improvement.

**Comment by bmwoodruff** [comment]
Unfortunately, the code you have does not run. You have not called the function using appropriate syntax.  This needs more work.
