### ISSUE TITLE
Task: Securely configure git for each user on Nebari.

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#5]
In order to read issues/comments/PRs via the GitHub API, we'll need to configure appropriate github authentications in Nebari. This let's us each make 5000 API calls per hour instead of just 60. 

@Adam-D-Lewis, Before i start configuring git on Nebari, are there any things I should be aware of?

**Comment by Adam-D-Lewis** [comment]
Nothing comes to mind, but ping if you see something unexpected

**Comment by bmwoodruff** [comment]
We decided to use fine-grained PATs with very limited access.
