### ISSUE TITLE
Task: Find out why the build isn't working

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#52]
**Description:**

I just completed this, and wanted to ping @jud-sdev , @otieno-juma , @ogidig5 .  They updgrade the version of Nebari in the last day or so. They just downgraded it, and I can build the docs now. I'm hoping you guys can to!

Thanks @Adam-D-Lewis.

**Acceptance Criteria:**

- [x] `spin docs` works again.

**Comment by bmwoodruff** [comment]
```
build succeeded.

The HTML pages are in build/html.
python3.11 postprocess.py html build/html/*.html

Build finished. The HTML pages are in build/html.
```

**Comment by otieno-juma** [comment]
@bmwoodruff Thank you. I'm going to try building the docs again

**Comment by jud-sdev** [comment]
I tried it again, but got an error: Here is the screenshot of the error I got
![image](https://github.com/possee-org/genai-numpy/assets/147154874/1c32ceb1-d552-45d3-9da1-ffaba612360a)

**Comment by otieno-juma** [comment]
Mine is working oaky now

**Comment by jud-sdev** [comment]
It's for working for me now.
Thank you

**Comment by ogidig5** [comment]
It's also building for me

**Comment by bmwoodruff** [comment]
Looks like everyone is able to work again. I'll close this.
