### ISSUE TITLE
Tracking Examples: linalg and ma

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#60]
* Claim a group by making a comment below. 
* ~While Nebari is generating examples~ See the [log files](https://github.com/possee-org/genai-numpy/tree/main/examples/log) for the output from Llama3. Spend some time with the functions to see what they do.
* Some of these functions are NOT something we need to add examples to. You'll have to decide that.
* When you've finished the group of 10, check it off.

## np.linalg
np.linalgGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1          | Group 2          | Group 3          |
| ---------------- | ---------------- | ---------------- |
| cholesky         | lstsq            | slogdet          |
| cond             | matmul           | solve            |
| cross            | matrix_norm      | svd              |
| det              | matrix_power     | svdvals          |
| diagonal         | matrix_rank      | tensordot        |
| eig              | matrix_transpose | tensorinv        |
| eigh             | multi_dot        | tensorsolve      |
| eigvals          | norm             | trace            |
| eigvalsh         | outer            | vecdot           |
| inv              | pinv             | vector_norm      |

## np.ma
np.maGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3
- [ ] Group 4
- [ ] Group 5
- [ ] Group 6
- [ ] Group 7
- [ ] Group 8
- [ ] Group 9
- [ ] Group 10
- [ ] Group 11

| Group 1                  | Group 2                  | Group 3                  | Group 4                  | Group 5                  |
| ------------------------ | ------------------------ | ------------------------ | ------------------------ | ------------------------ |
| allclose                 | asanyarray               | compress_rows            | dot                      | getmask                  |
| allequal                 | asarray                  | compressed               | ediff1d                  | getmaskarray             |
| alltrue                  | average                  | concatenate              | filled                   | in1d                     |
| amax                     | choose                   | convolve                 | fix_invalid              | inner                    |
| amin                     | clump_masked             | correlate                | flatnotmasked_contiguous | innerproduct             |
| append                   | clump_unmasked           | count_masked             | flatnotmasked_edges      | intersect1d              |
| apply_along_axis         | common_fill_value        | cov                      | flatten_mask             | isMA                     |
| apply_over_axes          | compress_cols            | default_fill_value       | flatten_structured_array | isMaskedArray            |
| argsort                  | compress_nd              | diag                     | fromflex                 | is_mask                  |
| array                    | compress_rowcols         | diff                     | getdata                  | is_masked                |

| Group 6                  | Group 7                  | Group 8                  | Group 9                  | Group 10                 |
| ------------------------ | ------------------------ | ------------------------ | ------------------------ | ------------------------ |
| isarray                  | masked_all               | masked_object            | ndim                     | reshape                  |
| isin                     | masked_all_like          | masked_outside           | notmasked_contiguous     | resize                   |
| left_shift               | masked_equal             | masked_values            | notmasked_edges          | right_shift              |
| make_mask                | masked_greater           | masked_where             | outer                    | round                    |
| make_mask_descr          | masked_greater_equal     | max                      | outerproduct             | round_                   |
| make_mask_none           | masked_inside            | maximum_fill_value       | polyfit                  | set_fill_value           |
| mask_cols                | masked_invalid           | median                   | power                    | setdiff1d                |
| mask_or                  | masked_less              | min                      | ptp                      | setxor1d                 |
| mask_rowcols             | masked_less_equal        | minimum_fill_value       | put                      | shape                    |
| mask_rows                | masked_not_equal         | ndenumerate              | putmask                  | size                     |

| Group 11                 |
| ------------------------ |
| sometrue                 |
| sort                     |
| take                     |
| transpose                |
| union1d                  |
| unique                   |
| vander                   |
| where                    |
|                          |
|                          |

**Comment by otieno-juma** [comment]
@bmwoodruff I will work on group 1

**Comment by bmwoodruff** [comment]
@otieno-juma No need to tag me on these, but you will want to specify if you're working on linalg group 1, or ma group 1.

**Comment by jud-sdev** [comment]
I'll work on np.linalg group 2

**Comment by bmwoodruff** [comment]
Note that the output of Llama3-70B is now store in these [log files ](https://github.com/possee-org/genai-numpy/tree/main/examples/log).

**Comment by jud-sdev** [comment]
Here's what I got when I tried generating examples for lstsq function in group 2.
![image](https://github.com/possee-org/genai-numpy/assets/147154874/31f2bed1-b84c-40c5-b629-6139ff842686)

**Comment by bmwoodruff** [comment]
It looks like you haven't cloned this repo yet to Nebari.  You'll want to start with that.

**Comment by jud-sdev** [comment]
I've cloned the repo. I think the issue is related to the upgrade of Numpy.
Have you tried generating an example today?

**Comment by bmwoodruff** [comment]
All the examples have been generated already by AI. The log files are in the `possee-org/gen-ai` repo. 

The error message you see above has always shown when using Llama 3.  You can ignore it, and things still work.

**Comment by jud-sdev** [comment]
Okay, I get it. Thank you so much, I truly appreciate it!

**Comment by otieno-juma** [comment]
I'm going to work on ma group 9

**Comment by otieno-juma** [comment]
I will work on ma group 9

**Comment by otieno-juma** [comment]
I'm going to work on ma group 9

**Comment by bmwoodruff** [comment]
@otieno-juma For now, focus only on functions that have no examples in the code base.  You can manually select these with the example_post_processing.py file, and then generate just those. 

The Triage team does not want to review 1000 examples that are injected systematically throughout the entire codebase.  So while we have a tool that can do that, it isn't wanted in that form.

**Comment by bmwoodruff** [comment]
After discussion at the triage meeting, adding examples to every function in NumPy is not wanted.  Focus on just the functions that don't have examples.  After we review the prompt generator, and guarantee that the newly generated examples do indeed add something of more than just marginal value, we can revisit this topic.  I'm closing this issue for now.
