### ISSUE TITLE
Tracking Examples: polynomial modules

### ISSUE THREAD

**Issue by bmwoodruff** [possee-org/genai-numpy#62]
The `polynomial` submodule have a lot of similarities. When working with the submodules make sure you compare with the same-ish function from the other submodules. They all have slightly different names, but work towards the same purpose. Doing the same-ish functions from submodules, side-by-side could be useful. The tables were algorithmic-ally generated, so they don't reflect this thought. 

* Claim a group by making a comment below. 
* ~While Nebari is generating examples~ See the [log files](https://github.com/possee-org/genai-numpy/tree/main/examples/log) for the output from Llama3. Spend some time with the functions to see what they do.
* Some of these functions are NOT something we need to add examples to. You'll have to decide that.
* When you've finished the group of 10, check it off.

## np.polynomial
np.polynomialGroups:
- [ ] Group 1

| Group 1                |
| ---------------------- |
| set_default_printstyle |

## np.polynomial.chebyshev
np.polynomial.chebyshevGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1         | Group 2         | Group 3         |
| --------------- | --------------- | --------------- |
| cheb2poly       | chebint         | chebtrim        |
| chebadd         | chebinterpolate | chebval         |
| chebcompanion   | chebline        | chebval2d       |
| chebder         | chebmul         | chebval3d       |
| chebdiv         | chebmulx        | chebvander      |
| chebfit         | chebpow         | chebvander2d    |
| chebfromroots   | chebpts1        | chebvander3d    |
| chebgauss       | chebpts2        | chebweight      |
| chebgrid2d      | chebroots       | poly2cheb       |
| chebgrid3d      | chebsub         |                 |

## np.polynomial.hermite
np.polynomial.hermiteGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1       | Group 2       | Group 3       |
| ------------- | ------------- | ------------- |
| herm2poly     | hermint       | hermval3d     |
| hermadd       | hermline      | hermvander    |
| hermcompanion | hermmul       | hermvander2d  |
| hermder       | hermmulx      | hermvander3d  |
| hermdiv       | hermpow       | hermweight    |
| hermfit       | hermroots     | poly2herm     |
| hermfromroots | hermsub       |               |
| hermgauss     | hermtrim      |               |
| hermgrid2d    | hermval       |               |
| hermgrid3d    | hermval2d     |               |

## np.polynomial.hermite.e
np.polynomial.hermite.eGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1        | Group 2        | Group 3        |
| -------------- | -------------- | -------------- |
| herme2poly     | hermeint       | hermeval3d     |
| hermeadd       | hermeline      | hermevander    |
| hermecompanion | hermemul       | hermevander2d  |
| hermeder       | hermemulx      | hermevander3d  |
| hermediv       | hermepow       | hermeweight    |
| hermefit       | hermeroots     | poly2herme     |
| hermefromroots | hermesub       |                |
| hermegauss     | hermetrim      |                |
| hermegrid2d    | hermeval       |                |
| hermegrid3d    | hermeval2d     |                |

## np.polynomial.laguerre
np.polynomial.laguerreGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1      | Group 2      | Group 3      |
| ------------ | ------------ | ------------ |
| lag2poly     | lagint       | lagval3d     |
| lagadd       | lagline      | lagvander    |
| lagcompanion | lagmul       | lagvander2d  |
| lagder       | lagmulx      | lagvander3d  |
| lagdiv       | lagpow       | lagweight    |
| lagfit       | lagroots     | poly2lag     |
| lagfromroots | lagsub       |              |
| laggauss     | lagtrim      |              |
| laggrid2d    | lagval       |              |
| laggrid3d    | lagval2d     |              |

## np.polynomial.legendre
np.polynomial.legendreGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1      | Group 2      | Group 3      |
| ------------ | ------------ | ------------ |
| leg2poly     | legint       | legval3d     |
| legadd       | legline      | legvander    |
| legcompanion | legmul       | legvander2d  |
| legder       | legmulx      | legvander3d  |
| legdiv       | legpow       | legweight    |
| legfit       | legroots     | poly2leg     |
| legfromroots | legsub       |              |
| leggauss     | legtrim      |              |
| leggrid2d    | legval       |              |
| leggrid3d    | legval2d     |              |

## np.polynomial.polynomial
np.polynomial.polynomialGroups:
- [ ] Group 1
- [ ] Group 2
- [ ] Group 3

| Group 1          | Group 2          | Group 3          |
| ---------------- | ---------------- | ---------------- |
| polyadd          | polymul          | polyvander       |
| polycompanion    | polymulx         | polyvander2d     |
| polyder          | polypow          | polyvander3d     |
| polydiv          | polyroots        |                  |
| polyfit          | polysub          |                  |
| polyfromroots    | polytrim         |                  |
| polygrid2d       | polyval          |                  |
| polygrid3d       | polyval2d        |                  |
| polyint          | polyval3d        |                  |
| polyline         | polyvalfromroots |                  |

**Comment by andrewtggreene** [comment]
I will work on the legendre group 1

**Comment by bmwoodruff** [comment]
After discussion at the triage meeting, adding examples to every function in NumPy is not wanted.  Focus on just the functions that don't have examples.  After we review the prompt generator, and guarantee that the newly generated examples do indeed add something of more than just marginal value, we can revisit this topic.  I'm closing this issue for now.
