### ISSUE TITLE
Review: AI Gen Examples for ma.reshape function

### ISSUE THREAD

**Issue by otieno-juma** [possee-org/genai-numpy#83]
**Link to your fork:**

https://github.com/numpy/numpy/compare/main...otieno-juma:numpy:ai-examples-ma-reshape

**Checks**

```
spin build && python -m pip install . && spin docs && python tools/refguide_check.py --doctests
```
- [x] All tests have passed
- [x] A visual inspection of the generated docs is correct

**Acceptance Criteria:**

Close when the following are complete, in order:
- [x] Reviewed by @bmwoodruff
- [x] Any suggestions to fork have been merged.
- [x] Reviewed by Numpy Mainter:

When all tasks are complete:
- [x] Submitted as PR to NumPy.

![reshape fuction pic](https://github.com/possee-org/genai-numpy/assets/103896399/e145c282-da2a-49cd-b057-8982cb6c6c6d)

**Comment by bmwoodruff** [comment]
Looks good to me. @charris, this is ready for your review.
