### ISSUE TITLE
Task: Working on the functions from polynomial.legendre group 1

### ISSUE THREAD

**Issue by andrewtggreene** [possee-org/genai-numpy#91]
**Description:**

Working on the following functions from polynomial.legendre
leg2poly
legadd
legcompanion
legder
legdiv
legfit
legfromroots
leggauss
leggrid2d
leggrid3d

**Acceptance Criteria:**

- [ ] List things here.

**Comment by bmwoodruff** [comment]
@andrewtggreene , did you see the comment in the Tracking list to work on these in groups?  The 6 different polynomial types are similar. I think it's appropriate they have a consistent look. As you look at them, please compare/contrast with the other polynomial modules.
